version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.4
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mysite_test

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bundle install

      - run:
          name: Setup database
          command: |
            bin/rails db:prepare

      - run:
          name: Run tests
          command: |
            bin/rails test

      - run:
          name: Run Brakeman
          command: |
            bundle exec brakeman

      - run:
          name: Run Bundler Audit
          command: |
            bundle exec bundle-audit check --update

      - run:
          name: Run RuboCop
          command: |
            bundle exec rubocop

workflows:
  version: 2

  test:
    jobs:
      - test